# Generated by Django 2.0.5 on 2018-06-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20180604_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, unique=True)),
                ('user_pwd', models.CharField(max_length=6)),
            ],
        ),
    ]
